# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7230136d323f6982057eeb77186de56e9e981da5251f7211f1d4328e20817629adce67c542cf3b9b6a9c30dc20242574b08b5fcd5052019ded87e98cf512a979

test:
  secret_key_base: f3ec58dd7684125e6476b7fc755504246c886aa9babb362417b979493e9ebe6b9e08467a677467761a4b9604be08b745a69bfa234140c0f29dcfd87bbfda0bac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
